/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EncodingTestInterface extends Interface {
  getFunction(
    nameOrSignature: "decodeRecipient" | "getExtensionData" | "getFlatEncoding"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeRecipient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExtensionData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlatEncoding",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExtensionData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlatEncoding",
    data: BytesLike
  ): Result;
}

export interface EncodingTest extends BaseContract {
  connect(runner?: ContractRunner | null): EncodingTest;
  waitForDeployment(): Promise<this>;

  interface: EncodingTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decodeRecipient: TypedContractMethod<[data: BytesLike], [string], "view">;

  getExtensionData: TypedContractMethod<
    [recipient: AddressLike],
    [string],
    "view"
  >;

  getFlatEncoding: TypedContractMethod<
    [recipient: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decodeRecipient"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getExtensionData"
  ): TypedContractMethod<[recipient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getFlatEncoding"
  ): TypedContractMethod<[recipient: AddressLike], [string], "view">;

  filters: {};
}
