/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClankerIndex } from "./ClankerIndex";
export type { IClankerFactory } from "./IClankerFactory";
