/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cabalTbaSol from "./CabalTBA.sol";
export type { cabalTbaSol };
import type * as diamond from "./diamond";
export type { diamond };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CabalNFT } from "./CabalNFT";
