/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC173__factory } from "./IERC173__factory";
export { OwnershipFacet__factory } from "./OwnershipFacet__factory";
