/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  ReceiverFacet,
  ReceiverFacetInterface,
} from "../../../../../contracts/cabal/diamond/facets/ReceiverFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346015576102c3908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c90816301ffc9a71461019557508063150b7a021461013e578063bc197c81146100a35763f23a6e6114610048575f80fd5b3461009f5760a036600319011261009f576100616101e8565b5061006a61020b565b5060843567ffffffffffffffff811161009f5761008b90369060040161022e565b505060405163f23a6e6160e01b8152602090f35b5f80fd5b3461009f5760a036600319011261009f576100bc6101e8565b506100c561020b565b5060443567ffffffffffffffff811161009f576100e690369060040161025c565b505060643567ffffffffffffffff811161009f5761010890369060040161025c565b505060843567ffffffffffffffff811161009f5761012a90369060040161022e565b505060405163bc197c8160e01b8152602090f35b3461009f57608036600319011261009f576101576101e8565b5061016061020b565b5060643567ffffffffffffffff811161009f5761018190369060040161022e565b5050604051630a85bd0160e11b8152602090f35b3461009f57602036600319011261009f576004359063ffffffff60e01b821680920361009f57602091630a85bd0160e11b81149081156101d7575b5015158152f35b630271189760e51b149050836101d0565b6004359073ffffffffffffffffffffffffffffffffffffffff8216820361009f57565b6024359073ffffffffffffffffffffffffffffffffffffffff8216820361009f57565b9181601f8401121561009f5782359167ffffffffffffffff831161009f576020838186019501011161009f57565b9181601f8401121561009f5782359167ffffffffffffffff831161009f576020808501948460051b01011161009f5756fea26469706673582212208fa4ea819f1e48e7418ed9b4d444883a91c1b30d2d9742e67ace52bffe3020b164736f6c634300081a0033";

type ReceiverFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReceiverFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReceiverFacet__factory extends ContractFactory {
  constructor(...args: ReceiverFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReceiverFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReceiverFacet__factory {
    return super.connect(runner) as ReceiverFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReceiverFacetInterface {
    return new Interface(_abi) as ReceiverFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReceiverFacet {
    return new Contract(address, _abi, runner) as unknown as ReceiverFacet;
  }
}
