/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  ReceiverFacet,
  ReceiverFacetInterface,
} from "../../../../../contracts/cabal/diamond/facets/ReceiverFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576102ab908161001c8239f35b600080fdfe60808060405260048036101561001457600080fd5b600091823560e01c90816301ffc9a71461019157508063150b7a021461013a578063bc197c81146100ac5763f23a6e611461004e57600080fd5b346100a85760a03660031901126100a8576100676101e5565b50610070610200565b5060843567ffffffffffffffff81116100a4576100909250369101610216565b505060405163f23a6e6160e01b8152602090f35b8280fd5b5080fd5b50346100a85760a03660031901126100a8576100c66101e5565b506100cf610200565b5067ffffffffffffffff604435818111610136576100f09036908401610244565b5050606435818111610136576101099036908401610244565b50506084359081116100a4576101229250369101610216565b505060405163bc197c8160e01b8152602090f35b8380fd5b50346100a85760803660031901126100a8576101546101e5565b5061015d610200565b5060643567ffffffffffffffff81116100a45761017d9250369101610216565b5050604051630a85bd0160e11b8152602090f35b919050346100a45760203660031901126100a4573563ffffffff60e01b81168091036100a45760209250630a85bd0160e11b81149081156101d4575b5015158152f35b630271189760e51b149050386101cd565b600435906001600160a01b03821682036101fb57565b600080fd5b602435906001600160a01b03821682036101fb57565b9181601f840112156101fb5782359167ffffffffffffffff83116101fb57602083818601950101116101fb57565b9181601f840112156101fb5782359167ffffffffffffffff83116101fb576020808501948460051b0101116101fb5756fea2646970667358221220eb1b8dcf1bf1bc273cccef6a93c7783a8ae39ccb3d428f29620ff535a1b1e1e364736f6c63430008140033";

type ReceiverFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReceiverFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReceiverFacet__factory extends ContractFactory {
  constructor(...args: ReceiverFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReceiverFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReceiverFacet__factory {
    return super.connect(runner) as ReceiverFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReceiverFacetInterface {
    return new Interface(_abi) as ReceiverFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReceiverFacet {
    return new Contract(address, _abi, runner) as unknown as ReceiverFacet;
  }
}
