/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  StorageRepairFacet,
  StorageRepairFacetInterface,
} from "../../../../../contracts/cabal/diamond/facets/StorageRepairFacet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "nextCabalId",
        type: "uint256",
      },
    ],
    name: "StorageRepaired",
    type: "event",
  },
  {
    inputs: [],
    name: "checkStorage",
    outputs: [
      {
        internalType: "uint256",
        name: "nextCabalId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "allCabalIdsLength",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "correctNextCabalId",
        type: "uint256",
      },
    ],
    name: "repairStorage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346015576101e2908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081631e1763d31461014b575063e06a859c14610032575f80fd5b346101475760203660031901126101475760043573ffffffffffffffffffffffffffffffffffffffff7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c1320541633036100f7576020817fbca70f10f4ad08caf10d6e67cedc63d9834ce15a6d7d5e54528cebc3221f4c3d927ff6b912f89c06d8afd06b9fa8bd742c729f30156da50b94481faddbc9d0b4e9e9555f7ff6b912f89c06d8afd06b9fa8bd742c729f30156da50b94481faddbc9d0b4e9ea55604051908152a1005b60405162461bcd60e51b815260206004820152602260248201527f4c69624469616d6f6e643a204d75737420626520636f6e7472616374206f776e60448201526132b960f11b6064820152608490fd5b5f80fd5b34610147575f366003190112610147576040907ff6b912f89c06d8afd06b9fa8bd742c729f30156da50b94481faddbc9d0b4e9e9547ff6b912f89c06d8afd06b9fa8bd742c729f30156da50b94481faddbc9d0b4e9ea549082526020820152f3fea264697066735822122055ac33abc04479ef48686ef3f376f9368c7ab02b11337299f943cde908f9cf2f64736f6c634300081a0033";

type StorageRepairFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StorageRepairFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StorageRepairFacet__factory extends ContractFactory {
  constructor(...args: StorageRepairFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      StorageRepairFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StorageRepairFacet__factory {
    return super.connect(runner) as StorageRepairFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StorageRepairFacetInterface {
    return new Interface(_abi) as StorageRepairFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StorageRepairFacet {
    return new Contract(address, _abi, runner) as unknown as StorageRepairFacet;
  }
}
