/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace IPoolManager {
  export type PoolKeyStruct = {
    currency0: AddressLike;
    currency1: AddressLike;
    fee: BigNumberish;
    tickSpacing: BigNumberish;
    hooks: AddressLike;
  };

  export type PoolKeyStructOutput = [
    currency0: string,
    currency1: string,
    fee: bigint,
    tickSpacing: bigint,
    hooks: string
  ] & {
    currency0: string;
    currency1: string;
    fee: bigint;
    tickSpacing: bigint;
    hooks: string;
  };
}

export declare namespace IV4Quoter {
  export type QuoteExactInputSingleParamsStruct = {
    poolKey: IPoolManager.PoolKeyStruct;
    zeroForOne: boolean;
    exactAmount: BigNumberish;
    hookData: BytesLike;
  };

  export type QuoteExactInputSingleParamsStructOutput = [
    poolKey: IPoolManager.PoolKeyStructOutput,
    zeroForOne: boolean,
    exactAmount: bigint,
    hookData: string
  ] & {
    poolKey: IPoolManager.PoolKeyStructOutput;
    zeroForOne: boolean;
    exactAmount: bigint;
    hookData: string;
  };
}

export interface IV4QuoterInterface extends Interface {
  getFunction(nameOrSignature: "quoteExactInputSingle"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "quoteExactInputSingle",
    values: [IV4Quoter.QuoteExactInputSingleParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "quoteExactInputSingle",
    data: BytesLike
  ): Result;
}

export interface IV4Quoter extends BaseContract {
  connect(runner?: ContractRunner | null): IV4Quoter;
  waitForDeployment(): Promise<this>;

  interface: IV4QuoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  quoteExactInputSingle: TypedContractMethod<
    [params: IV4Quoter.QuoteExactInputSingleParamsStruct],
    [[bigint, bigint] & { amountOut: bigint; gasEstimate: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "quoteExactInputSingle"
  ): TypedContractMethod<
    [params: IV4Quoter.QuoteExactInputSingleParamsStruct],
    [[bigint, bigint] & { amountOut: bigint; gasEstimate: bigint }],
    "nonpayable"
  >;

  filters: {};
}
