/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Hooks,
  HooksInterface,
} from "../../../../../@uniswap/v4-core/src/libraries/Hooks";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "hooks",
        type: "address",
      },
    ],
    name: "HookAddressNotValid",
    type: "error",
  },
  {
    inputs: [],
    name: "HookCallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "HookDeltaExceedsSwapAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidHookResponse",
    type: "error",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220ffd258dee02cceecddc2a27f0124b60e4a10fdb83372aba14fcc563d1b2a03ea64736f6c634300081a0033";

type HooksConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HooksConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Hooks__factory extends ContractFactory {
  constructor(...args: HooksConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Hooks & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Hooks__factory {
    return super.connect(runner) as Hooks__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HooksInterface {
    return new Interface(_abi) as HooksInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Hooks {
    return new Contract(address, _abi, runner) as unknown as Hooks;
  }
}
