/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type GovernanceSettingsStruct = {
  votingPeriod: BigNumberish;
  quorumBps: BigNumberish;
  majorityBps: BigNumberish;
  proposalThreshold: BigNumberish;
};

export type GovernanceSettingsStructOutput = [
  votingPeriod: bigint,
  quorumBps: bigint,
  majorityBps: bigint,
  proposalThreshold: bigint
] & {
  votingPeriod: bigint;
  quorumBps: bigint;
  majorityBps: bigint;
  proposalThreshold: bigint;
};

export interface CabalCreationFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTokens"
      | "contribute"
      | "createCabal"
      | "finalizeCabal"
      | "getClaimable"
      | "getContributors"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CabalCreated"
      | "CabalFinalized"
      | "Contributed"
      | "TokensClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCabal",
    values: [string, string, string, GovernanceSettingsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeCabal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimable",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributors",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCabal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCabal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributors",
    data: BytesLike
  ): Result;
}

export namespace CabalCreatedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    creator: AddressLike,
    name: string,
    symbol: string,
    tbaAddress: AddressLike
  ];
  export type OutputTuple = [
    cabalId: bigint,
    creator: string,
    name: string,
    symbol: string,
    tbaAddress: string
  ];
  export interface OutputObject {
    cabalId: bigint;
    creator: string;
    name: string;
    symbol: string;
    tbaAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CabalFinalizedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    tokenAddress: AddressLike,
    totalRaised: BigNumberish,
    titheAmount: BigNumberish,
    devBuyAmount: BigNumberish
  ];
  export type OutputTuple = [
    cabalId: bigint,
    tokenAddress: string,
    totalRaised: bigint,
    titheAmount: bigint,
    devBuyAmount: bigint
  ];
  export interface OutputObject {
    cabalId: bigint;
    tokenAddress: string;
    totalRaised: bigint;
    titheAmount: bigint;
    devBuyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [
    cabalId: bigint,
    contributor: string,
    amount: bigint,
    totalRaised: bigint
  ];
  export interface OutputObject {
    cabalId: bigint;
    contributor: string;
    amount: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    claimant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [cabalId: bigint, claimant: string, amount: bigint];
  export interface OutputObject {
    cabalId: bigint;
    claimant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CabalCreationFacet extends BaseContract {
  connect(runner?: ContractRunner | null): CabalCreationFacet;
  waitForDeployment(): Promise<this>;

  interface: CabalCreationFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTokens: TypedContractMethod<
    [cabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  contribute: TypedContractMethod<[cabalId: BigNumberish], [void], "payable">;

  createCabal: TypedContractMethod<
    [
      name: string,
      symbol: string,
      image: string,
      settings: GovernanceSettingsStruct
    ],
    [bigint],
    "nonpayable"
  >;

  finalizeCabal: TypedContractMethod<
    [cabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getClaimable: TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getContributors: TypedContractMethod<
    [cabalId: BigNumberish],
    [string[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTokens"
  ): TypedContractMethod<[cabalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[cabalId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "createCabal"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      image: string,
      settings: GovernanceSettingsStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeCabal"
  ): TypedContractMethod<[cabalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimable"
  ): TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributors"
  ): TypedContractMethod<[cabalId: BigNumberish], [string[]], "view">;

  getEvent(
    key: "CabalCreated"
  ): TypedContractEvent<
    CabalCreatedEvent.InputTuple,
    CabalCreatedEvent.OutputTuple,
    CabalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CabalFinalized"
  ): TypedContractEvent<
    CabalFinalizedEvent.InputTuple,
    CabalFinalizedEvent.OutputTuple,
    CabalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "Contributed"
  ): TypedContractEvent<
    ContributedEvent.InputTuple,
    ContributedEvent.OutputTuple,
    ContributedEvent.OutputObject
  >;
  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;

  filters: {
    "CabalCreated(uint256,address,string,string,address)": TypedContractEvent<
      CabalCreatedEvent.InputTuple,
      CabalCreatedEvent.OutputTuple,
      CabalCreatedEvent.OutputObject
    >;
    CabalCreated: TypedContractEvent<
      CabalCreatedEvent.InputTuple,
      CabalCreatedEvent.OutputTuple,
      CabalCreatedEvent.OutputObject
    >;

    "CabalFinalized(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      CabalFinalizedEvent.InputTuple,
      CabalFinalizedEvent.OutputTuple,
      CabalFinalizedEvent.OutputObject
    >;
    CabalFinalized: TypedContractEvent<
      CabalFinalizedEvent.InputTuple,
      CabalFinalizedEvent.OutputTuple,
      CabalFinalizedEvent.OutputObject
    >;

    "Contributed(uint256,address,uint256,uint256)": TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;
    Contributed: TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;

    "TokensClaimed(uint256,address,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
  };
}
