/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface GovernanceFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelProposal"
      | "createProposal"
      | "executeProposal"
      | "getNextProposalId"
      | "getProposal"
      | "getProposalState"
      | "hasVoted"
      | "proposeBuyTokens"
      | "proposeContributeToPresale"
      | "proposeCreateChildCabal"
      | "proposeDissolveChild"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalCancelled"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, AddressLike[], BigNumberish[], BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextProposalId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalState",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeBuyTokens",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeContributeToPresale",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeCreateChildCabal",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeDissolveChild",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextProposalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeBuyTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeContributeToPresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeCreateChildCabal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeDissolveChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [cabalId: BigNumberish, proposalId: BigNumberish];
  export type OutputTuple = [cabalId: bigint, proposalId: bigint];
  export interface OutputObject {
    cabalId: bigint;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    proposalId: BigNumberish,
    proposer: AddressLike,
    targets: AddressLike[],
    values: BigNumberish[],
    calldatas: BytesLike[],
    description: string,
    startBlock: BigNumberish,
    endBlock: BigNumberish
  ];
  export type OutputTuple = [
    cabalId: bigint,
    proposalId: bigint,
    proposer: string,
    targets: string[],
    values: bigint[],
    calldatas: string[],
    description: string,
    startBlock: bigint,
    endBlock: bigint
  ];
  export interface OutputObject {
    cabalId: bigint;
    proposalId: bigint;
    proposer: string;
    targets: string[];
    values: bigint[];
    calldatas: string[];
    description: string;
    startBlock: bigint;
    endBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [cabalId: BigNumberish, proposalId: BigNumberish];
  export type OutputTuple = [cabalId: bigint, proposalId: bigint];
  export interface OutputObject {
    cabalId: bigint;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    proposalId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    cabalId: bigint,
    proposalId: bigint,
    voter: string,
    support: boolean,
    weight: bigint
  ];
  export interface OutputObject {
    cabalId: bigint;
    proposalId: bigint;
    voter: string;
    support: boolean;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceFacet extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceFacet;
  waitForDeployment(): Promise<this>;

  interface: GovernanceFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelProposal: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      cabalId: BigNumberish,
      targets: AddressLike[],
      values: BigNumberish[],
      calldatas: BytesLike[],
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  executeProposal: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getNextProposalId: TypedContractMethod<
    [cabalId: BigNumberish],
    [bigint],
    "view"
  >;

  getProposal: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        id: bigint;
        proposer: string;
        forVotes: bigint;
        againstVotes: bigint;
        startBlock: bigint;
        endBlock: bigint;
        executed: boolean;
        cancelled: boolean;
        description: string;
      }
    ],
    "view"
  >;

  getProposalState: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  proposeBuyTokens: TypedContractMethod<
    [
      cabalId: BigNumberish,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish,
      minAmountOut: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  proposeContributeToPresale: TypedContractMethod<
    [
      cabalId: BigNumberish,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  proposeCreateChildCabal: TypedContractMethod<
    [cabalId: BigNumberish, ethContribution: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;

  proposeDissolveChild: TypedContractMethod<
    [cabalId: BigNumberish, childCabalId: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      cabalId: BigNumberish,
      targets: AddressLike[],
      values: BigNumberish[],
      calldatas: BytesLike[],
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNextProposalId"
  ): TypedContractMethod<[cabalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        id: bigint;
        proposer: string;
        forVotes: bigint;
        againstVotes: bigint;
        startBlock: bigint;
        endBlock: bigint;
        executed: boolean;
        cancelled: boolean;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalState"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeBuyTokens"
  ): TypedContractMethod<
    [
      cabalId: BigNumberish,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish,
      minAmountOut: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeContributeToPresale"
  ): TypedContractMethod<
    [
      cabalId: BigNumberish,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeCreateChildCabal"
  ): TypedContractMethod<
    [cabalId: BigNumberish, ethContribution: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeDissolveChild"
  ): TypedContractMethod<
    [cabalId: BigNumberish, childCabalId: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [cabalId: BigNumberish, proposalId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ProposalCancelled(uint256,uint256)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "ProposalCreated(uint256,uint256,address,address[],uint256[],bytes[],string,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256,uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "VoteCast(uint256,uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
