/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type GovernanceSettingsStruct = {
  votingPeriod: BigNumberish;
  quorumBps: BigNumberish;
  majorityBps: BigNumberish;
  proposalThreshold: BigNumberish;
};

export type GovernanceSettingsStructOutput = [
  votingPeriod: bigint,
  quorumBps: bigint,
  majorityBps: bigint,
  proposalThreshold: bigint
] & {
  votingPeriod: bigint;
  quorumBps: bigint;
  majorityBps: bigint;
  proposalThreshold: bigint;
};

export interface SettingsFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getClankerAddresses"
      | "getContractAddresses"
      | "getGovernanceSettings"
      | "initializeAddresses"
      | "initializeClankerAddresses"
      | "pauseCabal"
      | "unpauseCabal"
      | "updateContractAddress"
      | "updateGovernanceSettings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CabalPaused"
      | "CabalUnpaused"
      | "ContractAddressUpdated"
      | "GovernanceSettingsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getClankerAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernanceSettings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeAddresses",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeClankerAddresses",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseCabal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseCabal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContractAddress",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGovernanceSettings",
    values: [BigNumberish, GovernanceSettingsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getClankerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernanceSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeClankerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseCabal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpauseCabal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGovernanceSettings",
    data: BytesLike
  ): Result;
}

export namespace CabalPausedEvent {
  export type InputTuple = [cabalId: BigNumberish];
  export type OutputTuple = [cabalId: bigint];
  export interface OutputObject {
    cabalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CabalUnpausedEvent {
  export type InputTuple = [cabalId: BigNumberish];
  export type OutputTuple = [cabalId: bigint];
  export interface OutputObject {
    cabalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractAddressUpdatedEvent {
  export type InputTuple = [name: string, newAddress: AddressLike];
  export type OutputTuple = [name: string, newAddress: string];
  export interface OutputObject {
    name: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceSettingsUpdatedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    votingPeriod: BigNumberish,
    quorumBps: BigNumberish,
    majorityBps: BigNumberish,
    proposalThreshold: BigNumberish
  ];
  export type OutputTuple = [
    cabalId: bigint,
    votingPeriod: bigint,
    quorumBps: bigint,
    majorityBps: bigint,
    proposalThreshold: bigint
  ];
  export interface OutputObject {
    cabalId: bigint;
    votingPeriod: bigint;
    quorumBps: bigint;
    majorityBps: bigint;
    proposalThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettingsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): SettingsFacet;
  waitForDeployment(): Promise<this>;

  interface: SettingsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getClankerAddresses: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        clankerHook: string;
        clankerLocker: string;
        clankerMevModule: string;
        clankerDevBuyExtension: string;
      }
    ],
    "view"
  >;

  getContractAddresses: TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string] & {
        cabalNFT: string;
        tbaImplementation: string;
        erc6551Registry: string;
        clankerFactory: string;
        clankerFeeLocker: string;
        weth: string;
      }
    ],
    "view"
  >;

  getGovernanceSettings: TypedContractMethod<
    [cabalId: BigNumberish],
    [GovernanceSettingsStructOutput],
    "view"
  >;

  initializeAddresses: TypedContractMethod<
    [
      cabalNFT: AddressLike,
      tbaImplementation: AddressLike,
      erc6551Registry: AddressLike,
      clankerFactory: AddressLike,
      clankerFeeLocker: AddressLike,
      weth: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initializeClankerAddresses: TypedContractMethod<
    [
      clankerHook: AddressLike,
      clankerLocker: AddressLike,
      clankerMevModule: AddressLike,
      clankerDevBuyExtension: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  pauseCabal: TypedContractMethod<
    [cabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpauseCabal: TypedContractMethod<
    [cabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateContractAddress: TypedContractMethod<
    [name: string, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGovernanceSettings: TypedContractMethod<
    [cabalId: BigNumberish, newSettings: GovernanceSettingsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getClankerAddresses"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        clankerHook: string;
        clankerLocker: string;
        clankerMevModule: string;
        clankerDevBuyExtension: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractAddresses"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string] & {
        cabalNFT: string;
        tbaImplementation: string;
        erc6551Registry: string;
        clankerFactory: string;
        clankerFeeLocker: string;
        weth: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGovernanceSettings"
  ): TypedContractMethod<
    [cabalId: BigNumberish],
    [GovernanceSettingsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeAddresses"
  ): TypedContractMethod<
    [
      cabalNFT: AddressLike,
      tbaImplementation: AddressLike,
      erc6551Registry: AddressLike,
      clankerFactory: AddressLike,
      clankerFeeLocker: AddressLike,
      weth: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeClankerAddresses"
  ): TypedContractMethod<
    [
      clankerHook: AddressLike,
      clankerLocker: AddressLike,
      clankerMevModule: AddressLike,
      clankerDevBuyExtension: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pauseCabal"
  ): TypedContractMethod<[cabalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseCabal"
  ): TypedContractMethod<[cabalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContractAddress"
  ): TypedContractMethod<
    [name: string, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateGovernanceSettings"
  ): TypedContractMethod<
    [cabalId: BigNumberish, newSettings: GovernanceSettingsStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CabalPaused"
  ): TypedContractEvent<
    CabalPausedEvent.InputTuple,
    CabalPausedEvent.OutputTuple,
    CabalPausedEvent.OutputObject
  >;
  getEvent(
    key: "CabalUnpaused"
  ): TypedContractEvent<
    CabalUnpausedEvent.InputTuple,
    CabalUnpausedEvent.OutputTuple,
    CabalUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractAddressUpdated"
  ): TypedContractEvent<
    ContractAddressUpdatedEvent.InputTuple,
    ContractAddressUpdatedEvent.OutputTuple,
    ContractAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceSettingsUpdated"
  ): TypedContractEvent<
    GovernanceSettingsUpdatedEvent.InputTuple,
    GovernanceSettingsUpdatedEvent.OutputTuple,
    GovernanceSettingsUpdatedEvent.OutputObject
  >;

  filters: {
    "CabalPaused(uint256)": TypedContractEvent<
      CabalPausedEvent.InputTuple,
      CabalPausedEvent.OutputTuple,
      CabalPausedEvent.OutputObject
    >;
    CabalPaused: TypedContractEvent<
      CabalPausedEvent.InputTuple,
      CabalPausedEvent.OutputTuple,
      CabalPausedEvent.OutputObject
    >;

    "CabalUnpaused(uint256)": TypedContractEvent<
      CabalUnpausedEvent.InputTuple,
      CabalUnpausedEvent.OutputTuple,
      CabalUnpausedEvent.OutputObject
    >;
    CabalUnpaused: TypedContractEvent<
      CabalUnpausedEvent.InputTuple,
      CabalUnpausedEvent.OutputTuple,
      CabalUnpausedEvent.OutputObject
    >;

    "ContractAddressUpdated(string,address)": TypedContractEvent<
      ContractAddressUpdatedEvent.InputTuple,
      ContractAddressUpdatedEvent.OutputTuple,
      ContractAddressUpdatedEvent.OutputObject
    >;
    ContractAddressUpdated: TypedContractEvent<
      ContractAddressUpdatedEvent.InputTuple,
      ContractAddressUpdatedEvent.OutputTuple,
      ContractAddressUpdatedEvent.OutputObject
    >;

    "GovernanceSettingsUpdated(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      GovernanceSettingsUpdatedEvent.InputTuple,
      GovernanceSettingsUpdatedEvent.OutputTuple,
      GovernanceSettingsUpdatedEvent.OutputObject
    >;
    GovernanceSettingsUpdated: TypedContractEvent<
      GovernanceSettingsUpdatedEvent.InputTuple,
      GovernanceSettingsUpdatedEvent.OutputTuple,
      GovernanceSettingsUpdatedEvent.OutputObject
    >;
  };
}
