/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface StorageRepairFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "checkStorage" | "repairStorage"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StorageRepaired"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repairStorage",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repairStorage",
    data: BytesLike
  ): Result;
}

export namespace StorageRepairedEvent {
  export type InputTuple = [nextCabalId: BigNumberish];
  export type OutputTuple = [nextCabalId: bigint];
  export interface OutputObject {
    nextCabalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageRepairFacet extends BaseContract {
  connect(runner?: ContractRunner | null): StorageRepairFacet;
  waitForDeployment(): Promise<this>;

  interface: StorageRepairFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkStorage: TypedContractMethod<
    [],
    [[bigint, bigint] & { nextCabalId: bigint; allCabalIdsLength: bigint }],
    "view"
  >;

  repairStorage: TypedContractMethod<
    [correctNextCabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkStorage"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { nextCabalId: bigint; allCabalIdsLength: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "repairStorage"
  ): TypedContractMethod<
    [correctNextCabalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "StorageRepaired"
  ): TypedContractEvent<
    StorageRepairedEvent.InputTuple,
    StorageRepairedEvent.OutputTuple,
    StorageRepairedEvent.OutputObject
  >;

  filters: {
    "StorageRepaired(uint256)": TypedContractEvent<
      StorageRepairedEvent.InputTuple,
      StorageRepairedEvent.OutputTuple,
      StorageRepairedEvent.OutputObject
    >;
    StorageRepaired: TypedContractEvent<
      StorageRepairedEvent.InputTuple,
      StorageRepairedEvent.OutputTuple,
      StorageRepairedEvent.OutputObject
    >;
  };
}
