/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type GovernanceSettingsStruct = {
  votingPeriod: BigNumberish;
  quorumBps: BigNumberish;
  majorityBps: BigNumberish;
  proposalThreshold: BigNumberish;
};

export type GovernanceSettingsStructOutput = [
  votingPeriod: bigint,
  quorumBps: bigint,
  majorityBps: bigint,
  proposalThreshold: bigint
] & {
  votingPeriod: bigint;
  quorumBps: bigint;
  majorityBps: bigint;
  proposalThreshold: bigint;
};

export declare namespace ViewFacet {
  export type CabalInfoStruct = {
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    symbol: string;
    image: string;
    tbaAddress: AddressLike;
    tokenAddress: AddressLike;
    phase: BigNumberish;
    totalRaised: BigNumberish;
    totalTokensReceived: BigNumberish;
    totalStaked: BigNumberish;
    contributorCount: BigNumberish;
    settings: GovernanceSettingsStruct;
  };

  export type CabalInfoStructOutput = [
    id: bigint,
    creator: string,
    name: string,
    symbol: string,
    image: string,
    tbaAddress: string,
    tokenAddress: string,
    phase: bigint,
    totalRaised: bigint,
    totalTokensReceived: bigint,
    totalStaked: bigint,
    contributorCount: bigint,
    settings: GovernanceSettingsStructOutput
  ] & {
    id: bigint;
    creator: string;
    name: string;
    symbol: string;
    image: string;
    tbaAddress: string;
    tokenAddress: string;
    phase: bigint;
    totalRaised: bigint;
    totalTokensReceived: bigint;
    totalStaked: bigint;
    contributorCount: bigint;
    settings: GovernanceSettingsStructOutput;
  };
}

export interface ViewFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllCabals"
      | "getCabal"
      | "getCabals"
      | "getCabalsByCreator"
      | "getCabalsByStaker"
      | "getContribution"
      | "getTotalCabals"
      | "getUserPositions"
      | "hasClaimed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllCabals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCabal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCabals",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getCabalsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCabalsByStaker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCabals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllCabals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCabal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCabals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCabalsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCabalsByStaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCabals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
}

export interface ViewFacet extends BaseContract {
  connect(runner?: ContractRunner | null): ViewFacet;
  waitForDeployment(): Promise<this>;

  interface: ViewFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllCabals: TypedContractMethod<[], [bigint[]], "view">;

  getCabal: TypedContractMethod<
    [cabalId: BigNumberish],
    [ViewFacet.CabalInfoStructOutput],
    "view"
  >;

  getCabals: TypedContractMethod<
    [cabalIds: BigNumberish[]],
    [ViewFacet.CabalInfoStructOutput[]],
    "view"
  >;

  getCabalsByCreator: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getCabalsByStaker: TypedContractMethod<
    [staker: AddressLike],
    [bigint[]],
    "view"
  >;

  getContribution: TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getTotalCabals: TypedContractMethod<[], [bigint], "view">;

  getUserPositions: TypedContractMethod<
    [user: AddressLike, cabalIds: BigNumberish[]],
    [
      [bigint[], bigint[], bigint[], boolean[]] & {
        contributions: bigint[];
        stakedBalances: bigint[];
        votingPowers: bigint[];
        claimed: boolean[];
      }
    ],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllCabals"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCabal"
  ): TypedContractMethod<
    [cabalId: BigNumberish],
    [ViewFacet.CabalInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCabals"
  ): TypedContractMethod<
    [cabalIds: BigNumberish[]],
    [ViewFacet.CabalInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCabalsByCreator"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCabalsByStaker"
  ): TypedContractMethod<[staker: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalCabals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<
    [user: AddressLike, cabalIds: BigNumberish[]],
    [
      [bigint[], bigint[], bigint[], boolean[]] & {
        contributions: bigint[];
        stakedBalances: bigint[];
        votingPowers: bigint[];
        claimed: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [cabalId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  filters: {};
}
