/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  BalanceDeltaLibrary,
  BalanceDeltaLibraryInterface,
} from "../../../../../../@uniswap/v4-core/src/types/BalanceDelta.sol/BalanceDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BalanceDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234601b5760405160ba61002082393081505060ba90f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c6391cb466903602b576064565b5f910312602b57565b5f80fd5b6039603960399290565b90565b60395f602f565b6039603c565b605090602f565b9052565b602081019291606291906049565b565b606d3660046022565b608060756043565b604051918291826054565b0390f3fea2646970667358221220ac222c7244e4e5d924863c612902b095b3eef087e8a561a1b986fabd4f33f3c364736f6c634300081a0033";

type BalanceDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BalanceDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BalanceDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BalanceDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BalanceDeltaLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BalanceDeltaLibrary__factory {
    return super.connect(runner) as BalanceDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BalanceDeltaLibraryInterface {
    return new Interface(_abi) as BalanceDeltaLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BalanceDeltaLibrary {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BalanceDeltaLibrary;
  }
}
