/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { ClankerIndex } from "./contracts/ClankerIndex.sol/ClankerIndex";
export { ClankerIndex__factory } from "./factories/contracts/ClankerIndex.sol/ClankerIndex__factory";
export type { IClankerFactory } from "./contracts/ClankerIndex.sol/IClankerFactory";
export { IClankerFactory__factory } from "./factories/contracts/ClankerIndex.sol/IClankerFactory__factory";
