/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV4Router,
  IV4RouterInterface,
} from "../../../../../@uniswap/v4-periphery/src/interfaces/IV4Router";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minAmountOutReceived",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountReceived",
        type: "uint256",
      },
    ],
    name: "V4TooLittleReceived",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "maxAmountInRequested",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountRequested",
        type: "uint256",
      },
    ],
    name: "V4TooMuchRequested",
    type: "error",
  },
  {
    inputs: [],
    name: "poolManager",
    outputs: [
      {
        internalType: "contract IPoolManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IV4Router__factory {
  static readonly abi = _abi;
  static createInterface(): IV4RouterInterface {
    return new Interface(_abi) as IV4RouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IV4Router {
    return new Contract(address, _abi, runner) as unknown as IV4Router;
  }
}
