/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface TreasuryFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buildBuyTokenCalldata"
      | "buildInvestInPresaleCalldata"
      | "buildTransferETHCalldata"
      | "buildTransferTokenCalldata"
      | "claimLPFees"
      | "getClaimableLPFees"
      | "getOwnTokenBalance"
      | "getTreasuryETHBalance"
      | "getTreasuryTokenBalance"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LPFeesClaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "buildBuyTokenCalldata",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buildInvestInPresaleCalldata",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buildTransferETHCalldata",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buildTransferTokenCalldata",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLPFees",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableLPFees",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnTokenBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryETHBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryTokenBalance",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "buildBuyTokenCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildInvestInPresaleCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildTransferETHCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildTransferTokenCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimLPFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableLPFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryETHBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryTokenBalance",
    data: BytesLike
  ): Result;
}

export namespace LPFeesClaimedEvent {
  export type InputTuple = [
    cabalId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [cabalId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    cabalId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryFacet extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryFacet;
  waitForDeployment(): Promise<this>;

  interface: TreasuryFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buildBuyTokenCalldata: TypedContractMethod<
    [
      router: AddressLike,
      arg1: AddressLike,
      ethAmount: BigNumberish,
      minAmountOut: BigNumberish,
      deadline: BigNumberish
    ],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;

  buildInvestInPresaleCalldata: TypedContractMethod<
    [
      diamond: AddressLike,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish
    ],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;

  buildTransferETHCalldata: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;

  buildTransferTokenCalldata: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;

  claimLPFees: TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getClaimableLPFees: TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getOwnTokenBalance: TypedContractMethod<
    [cabalId: BigNumberish],
    [bigint],
    "view"
  >;

  getTreasuryETHBalance: TypedContractMethod<
    [cabalId: BigNumberish],
    [bigint],
    "view"
  >;

  getTreasuryTokenBalance: TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buildBuyTokenCalldata"
  ): TypedContractMethod<
    [
      router: AddressLike,
      arg1: AddressLike,
      ethAmount: BigNumberish,
      minAmountOut: BigNumberish,
      deadline: BigNumberish
    ],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buildInvestInPresaleCalldata"
  ): TypedContractMethod<
    [
      diamond: AddressLike,
      targetCabalId: BigNumberish,
      ethAmount: BigNumberish
    ],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buildTransferETHCalldata"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buildTransferTokenCalldata"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [
      [string, bigint, string] & { target: string; value: bigint; data: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimLPFees"
  ): TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimableLPFees"
  ): TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnTokenBalance"
  ): TypedContractMethod<[cabalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreasuryETHBalance"
  ): TypedContractMethod<[cabalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreasuryTokenBalance"
  ): TypedContractMethod<
    [cabalId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "LPFeesClaimed"
  ): TypedContractEvent<
    LPFeesClaimedEvent.InputTuple,
    LPFeesClaimedEvent.OutputTuple,
    LPFeesClaimedEvent.OutputObject
  >;

  filters: {
    "LPFeesClaimed(uint256,address,uint256)": TypedContractEvent<
      LPFeesClaimedEvent.InputTuple,
      LPFeesClaimedEvent.OutputTuple,
      LPFeesClaimedEvent.OutputObject
    >;
    LPFeesClaimed: TypedContractEvent<
      LPFeesClaimedEvent.InputTuple,
      LPFeesClaimedEvent.OutputTuple,
      LPFeesClaimedEvent.OutputObject
    >;
  };
}
