/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  CurrencyLibrary,
  CurrencyLibraryInterface,
} from "../../../../../../@uniswap/v4-core/src/types/Currency.sol/CurrencyLibrary";

const _abi = [
  {
    inputs: [],
    name: "ERC20TransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "NativeTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ADDRESS_ZERO",
    outputs: [
      {
        internalType: "Currency",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234601b5760405160f361002082393081505060f390f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c6366e7950903602b57609d565b5f910312602b57565b5f80fd5b603c603960399290565b90565b6001600160a01b031690565b603990602f565b603990603c906001600160a01b031682565b603990604f565b6039906061565b603960785f6048565b6068565b6039606f565b6089906068565b9052565b602081019291609b91906082565b565b60a63660046022565b60b960ae607c565b60405191829182608d565b0390f3fea26469706673582212205915101d0a03ea3eaa003634b7e80bf1ead8856ac108313c2e030a13cf445e0864736f6c634300081a0033";

type CurrencyLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CurrencyLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CurrencyLibrary__factory extends ContractFactory {
  constructor(...args: CurrencyLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CurrencyLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CurrencyLibrary__factory {
    return super.connect(runner) as CurrencyLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CurrencyLibraryInterface {
    return new Interface(_abi) as CurrencyLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CurrencyLibrary {
    return new Contract(address, _abi, runner) as unknown as CurrencyLibrary;
  }
}
