/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  BeforeSwapDeltaLibrary,
  BeforeSwapDeltaLibraryInterface,
} from "../../../../../../@uniswap/v4-core/src/types/BeforeSwapDelta.sol/BeforeSwapDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BeforeSwapDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601757606f9081601c823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c6391cb4669146023575f80fd5b5f366003190112603557805f60209252f35b5f80fdfea264697066735822122001e407f1bd491c6ed0e25ff43ab8377e2088d25a57464099fcd13b2e0591084264736f6c634300081a0033";

type BeforeSwapDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BeforeSwapDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BeforeSwapDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BeforeSwapDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BeforeSwapDeltaLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BeforeSwapDeltaLibrary__factory {
    return super.connect(runner) as BeforeSwapDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BeforeSwapDeltaLibraryInterface {
    return new Interface(_abi) as BeforeSwapDeltaLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BeforeSwapDeltaLibrary {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BeforeSwapDeltaLibrary;
  }
}
